-- -- Roles schema

-- -- !Ups

-- CREATE TABLE "POSTS"(
--    "ID" UUID PRIMARY KEY,
--    "MESSAGE" VARCHAR(255) NOT NULL,
--    "PASSWORD" VARCHAR(255) NOT NULL,
--    "PHOTO" BYTEA NOT NULL,
--    "EXTENSION" VARCHAR(255) NOT NULL,
--    "CREATED_AT" TIMESTAMP NOT NULL

-- );

-- -- !Downs

-- DROP TABLE "POSTS";